/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2021-07-07 01:58:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.src;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://unpkg.com/ress/dist/ress.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://pro.fontawesome.com/releases/v5.10.0/css/all.css\" integrity=\"sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p\" crossorigin=\"anonymous\"/>\r\n");
      out.write("\t<!-- JQuery -->\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("\t<!-- Menu Btn -->\r\n");
      out.write("\t<script> $(function() { $(\"#menubtn\").click(function(){ $(\"#menu\").slideToggle(); }); }); </script>\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"initial.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"main.css\">\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"../img/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("\t<link rel=\"icon\" href=\"../img/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("\t<title>Welcome to Shin`s Website</title>\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/src/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- [S] Movie -->\r\n");
      out.write("\t<div class=\"jb-box\">\r\n");
      out.write("\t\t<video muted autoplay loop>\r\n");
      out.write("\t\t\t<source src=\"../media/Keyboard.mp4\" type=\"video/mp4\" >\r\n");
      out.write("\t\t\t<strong>Your browser does not support the video tag.</strong>\r\n");
      out.write("\t\t</video>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"jb-text\">\r\n");
      out.write("\t\t\t<p class=\"vtext-big\">Hello World!</p>\r\n");
      out.write("\t\t\t<p class=\"vtext-small\">This Website made of JSP</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"scroll-downs\">\r\n");
      out.write("\t\t\t<div class=\"mousey\">\r\n");
      out.write("\t\t\t\t<div class=\"scroller\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- [E] Movie -->\r\n");
      out.write("\t<div class=\"margin-box\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"normal-box\">\r\n");
      out.write("\t\t<p class=\"normal-ntext csc\">Hallo!</p>\r\n");
      out.write("\t\t<p class=\"normal-btext csc margin-h2\">신승헌입니다.</p>\r\n");
      out.write("\t\t<p class=\"normal-ntext csc margin-h3\">신승헌 / Shin Seoung Heon / 1997년생 / 포항<br/>\r\n");
      out.write("\t\t\t강원대학교 / 컴퓨터공학과 <br/>\r\n");
      out.write("\t\t\t컴퓨터 / 프라모델 / 요리 / 게임 / 독서 <br/> \r\n");
      out.write("\t\t\t웹 / 인공지능 / 교육 / 디자인 / 미디어 / 마케팅\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<p class=\"normal-ltext csc margin-h3\"> 더 많은 정보는?</p>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"normal-btn margin-h3\">\r\n");
      out.write("\t\t\t<button class=\"normal-btn-inner normal-sltext\" onclick=\"location.href='#0'\">자세한 이야기</button>\r\n");
      out.write("\t\t\t<button class=\"normal-btn-inner normal-sltext\" onclick=\"location.href='introduce.jsp'\">더 알아보기</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"margin-box\" id=\"0\" style=\"margin-bottom: 20px;\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"normal-box\">\r\n");
      out.write("\t\t<div class=\"minfo-contents\">\r\n");
      out.write("\t\t\t<div class=\"mimg-left\">\r\n");
      out.write("\t\t\t\t<img src=\"../img/shin01.png\" alt=\"\" width=\"100%\" height=\"auto\" style=\"box-shadow:5px 5px 10px grey;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"mtext-right\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<h1 class=\"normal-nbtext\">포항 촌놈</h1>\r\n");
      out.write("\t\t\t\t\t<p class=\"normal-ltext margin-h2\">1997년 대구에서 태어나, 포항에서 초등학교, 중학교, 고등학교를 나왔습니다. 군대와 대학을 나오면서 많이 고쳐졌지만, 흥분하거나 무의식적으로 튀어나오는 특유의 경상도 사투리가 매력적입니다. 어릴 적부터 컴퓨터를 좋아하여, 진로를 IT계열로 잡아 강원대학교 컴퓨터공학과에 진학하였습니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"margin-box\"></div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"normal-box\">\t\t\r\n");
      out.write("\t\t<div class=\"minfo-contents margin-h3\">\r\n");
      out.write("\t\t\t<div class=\"mimg-right img-overlap\">\r\n");
      out.write("\t\t\t\t<div class=\"img-overlap-inner\">\r\n");
      out.write("\t\t\t\t\t<img class=\"img-01\" src=\"../img/hobby_01.jpg\" alt=\"\" width=\"100%\" height=\"auto\" style=\"box-shadow:5px 5px 10px grey;\">\r\n");
      out.write("\t\t\t\t\t<img class=\"img-02\" src=\"../img/hobby_02.jpg\" alt=\"\" width=\"100%\" height=\"auto\" style=\"box-shadow:5px 5px 10px grey;\">\r\n");
      out.write("\t\t\t\t\t<img class=\"img-03\" src=\"../img/hobby_03.jpg\" alt=\"\" width=\"100%\" height=\"auto\" style=\"box-shadow:5px 5px 10px grey;\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"mtext-left\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<h1 class=\"normal-nbtext\">최고의 <ruby>집<rt>.</rt>돌<rt>.</rt>이<rt>.</rt></ruby></h1>\r\n");
      out.write("\t\t\t\t\t<p class=\"normal-ltext margin-h2\">종종 컴퓨터 부품 시세를 보고 컴퓨터를 업그레이드하거나, 다른 사람의 견적을 맞춰주는 것을 좋아합니다. \r\n");
      out.write("\t\t\t\t\t\t먹고 싶은 음식이 있으면 사 먹는 것보다 해먹는 것을 좋아하고, 이미 조리된 음식을 다시 내 입맛대로 바꿔 먹는 것을 즐깁니다.\r\n");
      out.write("\t\t\t\t\t\t가끔 특가에 혹하여 구매한 프라모델과 며칠 간 씨름하기도 하고, 사락사락 책장을 넘기는 소리와 함께 소설속으로 빠져들기도 합니다.\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"margin-box\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"normal-box\">\r\n");
      out.write("\t\t<img src=\"../img/web.png\" alt=\"\" width=\"100%\" height=\"auto\" class=\"margin-h2\" style=\"box-shadow:5px 5px 10px grey;\">\r\n");
      out.write("\t\t<div class=\"minfo-contents\">\r\n");
      out.write("\t\t\t<div class=\"mimg-left\">\r\n");
      out.write("\t\t\t\t<img src=\"../img/ai.jpg\" alt=\"\" width=\"100%\" height=\"auto\" height=\"auto\" style=\"box-shadow:5px 5px 10px grey;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"mtext-right\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<h1 class=\"normal-nbtext\">아직도 하고 싶은게 많은!</h1>\r\n");
      out.write("\t\t\t\t\t<p class=\"normal-ltext margin-h2\">웹 개발 쪽에 관심이 많아 관련 HTML, CSS, JS를 조금씩 건드려보고 있다가, 파이썬을 활용한 웹 프레임워크가 좋다고 해서 배워보다가, 또 파이썬을 하다보니 인공지능에 흥미가 생기는 등, 끝없이 새로운 것에 도전하고 싶어집니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"margin-box\"></div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"normal-box\">\r\n");
      out.write("\t\t<h1 class=\"normal-ntext csc\">to be continue..!</h1>\r\n");
      out.write("\t\t<h2 class=\"normal-btext csc margin-h2\">신승헌의 도전은<br>계속됩니다!</h2>\r\n");
      out.write("\t\t<p class=\"normal-ltext csc margin-h3\">IT는 다른 어떤 분야보다 빠르게 변화하고 진화하는 분야입니다.<br>\r\n");
      out.write("\t\t\t또 어떤 신기하고 굉장한 기능이 저를 놀라게 할 수 있을지를 상상하며,<br>\r\n");
      out.write("\t\t\t저는 오늘도 새로운 분야를 도전하고 있습니다!\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<div class=\"normal-btn margin-h2\">\r\n");
      out.write("\t\t\t<button class=\"normal-btn-inner normal-sltext margin-h2\" onclick=\"location.href='portfolio.jsp'\">신승헌의 도전기</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"margin-box\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/src/footer.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/src/page_up_btn.jsp", out, false);
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
