/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2021-05-19 10:02:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.src;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class company_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String subject = "company";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://unpkg.com/ress/dist/ress.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://pro.fontawesome.com/releases/v5.10.0/css/all.css\" integrity=\"sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p\" crossorigin=\"anonymous\"/>\r\n");
      out.write("\t<!-- JQuery -->\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("\t<!-- Menu Btn -->\r\n");
      out.write("\t<script> $(function() { $(\"#menubtn\").click(function(){ $(\"#menu\").slideToggle(); }); }); </script>\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"../img/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("\t<link rel=\"icon\" href=\"../img/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<title>AngelPlayer Inc. | Company</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/src/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"jb-box\">\r\n");
      out.write("\t\t<div class=\"top-img\">\r\n");
      out.write("\t\t\t<img src=\"../img/");
      out.print(subject);
      out.write(".png\" alt=\"\" width=\"1920\" height=\"auto\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"jc-text\">\r\n");
      out.write("\t\t\t<p class=\"vtext-big\">");
      out.print(subject);
      out.write(" Us</p>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"contents\">\r\n");
      out.write("\t\t<div class=\"contents-1\">\r\n");
      out.write("\t\t\t<!-- 문서 작성 -->\r\n");
      out.write("\t\t\t<article class=\"story\">\r\n");
      out.write("\t\t\t\t<div class=\"bread\">\r\n");
      out.write("\t\t\t\t\t<ol>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"main.html\"><i class=\"fas fa-home\"></i> 메인</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">문의</a></li>\r\n");
      out.write("\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<h1 id=\"0\">Contact Us</h1>\r\n");
      out.write("\t\t\t\t<h2 id=\"1\">찾아오시는 길</h2>\r\n");
      out.write("\t\t\t\t<iframe src=\"https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12669.170578776471!2d129.1623725!3d37.4538118!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x759562fce995d5fe!2z6rCV7JuQ64yA7ZWZ6rWQIOyCvOyymey6oO2NvOyKpA!5e0!3m2!1sko!2skr!4v1621418529200!5m2!1sko!2skr\" width=\"100%\" height=\"600px\" style=\"border:0;\" allowfullscreen=\"\" loading=\"lazy\"></iframe>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<p><i class=\"fas fa-map-marker-alt\"></i>  경북 영천시 금호읍 대구대길 333 창업보육센터 2호관 1206호</p>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<h2 id=\"2\">연락처</h2>\r\n");
      out.write("\t\t\t\t<p><i class=\"fas fa-phone\"></i>  053)853-1608</p>\r\n");
      out.write("\t\t\t\t<p><i class=\"fas fa-fax\"></i>  053)853-1607</p>\r\n");
      out.write("\t\t\t\t<p><i class=\"fas fa-envelope\"></i>  airtech2019@naver.com</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t</article>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"contents-2\">\r\n");
      out.write("\t\t\t<!-- 사이드 메뉴 -->\r\n");
      out.write("\t\t\t<aside class=\"sidemenu\">\r\n");
      out.write("\t\t\t\t<h1><a href=\"#0\">Contact Us</a></h1>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#1\">찾아오시는 길</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#2\">연락처</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</aside>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/src/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
