/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2021-07-02 13:21:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.src;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class introduce_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://unpkg.com/ress/dist/ress.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://pro.fontawesome.com/releases/v5.10.0/css/all.css\" integrity=\"sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p\" crossorigin=\"anonymous\"/>\r\n");
      out.write("\t<!-- JQuery -->\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("\t<!-- Menu Btn -->\r\n");
      out.write("\t<script> $(function() { $(\"#menubtn\").click(function(){ $(\"#menu\").slideToggle(); }); }); </script>\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"initial.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"introduce.css\">\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"../img/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("\t<link rel=\"icon\" href=\"../img/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<title>About Shin</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/src/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"jb-box\">\r\n");
      out.write("\t\t<div class=\"top-img\">\r\n");
      out.write("\t\t\t<img src=\"../img/about_shin.png\" alt=\"\" width=\"1920\" height=\"auto\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"jc-text\">\r\n");
      out.write("\t\t\t<p class=\"vtext-big\">About Shin</p>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"margin-box\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"normal-box\">\r\n");
      out.write("\t\t<div class=\"about-box line-box\">\r\n");
      out.write("\t\t\t<div class=\"about-box-0\">\r\n");
      out.write("\t\t\t\t<h1 class=\"normal-ntext margin-p\" style=\"font-weight: bolder;\">인적사항</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"about-box-1\">\r\n");
      out.write("\t\t\t\t<div class=\"about-box-31\">\r\n");
      out.write("\t\t\t\t\t<p class=\"normal-sltext margin-p\" style=\"font-weight: bolder;\" >성명</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"about-box-32\">\r\n");
      out.write("\t\t\t\t\t<p class=\"normal-sltext margin-p\" >신승헌</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t<div class=\"about-box-31\">\r\n");
      out.write("\t\t\t\t\t<p class=\"normal-sltext margin-p\" style=\"font-weight: bolder;\" >생년월일</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"about-box-32\">\r\n");
      out.write("\t\t\t\t\t<p class=\"normal-sltext margin-p\" >1997. 08. 08</p>\r\n");
      out.write("\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"about-box-31\">\r\n");
      out.write("\t\t\t\t\t<p class=\"normal-sltext margin-p\" style=\"font-weight: bolder;\" >휴대폰</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"about-box-32\">\r\n");
      out.write("\t\t\t\t\t<p class=\"normal-sltext margin-p\" >010-0000-0000</p>\r\n");
      out.write("\t\t\t\t</div> \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"about-box-31\">\r\n");
      out.write("\t\t\t\t\t<p class=\"normal-sltext margin-p\" style=\"font-weight: bolder;\" >이메일</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"about-box-32\">\r\n");
      out.write("\t\t\t\t\t<p class=\"normal-sltext margin-p\" >angelplayers@naver.com</p>\r\n");
      out.write("\t\t\t\t</div> \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"about-box line-box\">\r\n");
      out.write("\t\t\t<div class=\"about-box-0\">\r\n");
      out.write("\t\t\t\t<h1 class=\"normal-ntext margin-p\" style=\"font-weight: bolder;\">학력사항</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"about-box-1\">\r\n");
      out.write("\t\t\t\t<p class=\"normal-sltext margin-p\" style=\"font-weight: bolder;\" >2013. 03 - 2016. 02</p>\r\n");
      out.write("\t\t\t\t<p class=\"normal-sltext\" style=\"margin-top: 5px;\" >포항 대동고등학교 졸업</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<p class=\"normal-sltext\" style=\"font-weight: bolder; margin-top: 30px;\" >2016. 03 - 2022. 02</p>\r\n");
      out.write("\t\t\t\t<p class=\"normal-sltext\" style=\"margin-top: 5px;\" >강원대학교 컴퓨터공학과 학사 졸업</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"about-box line-box\">\r\n");
      out.write("\t\t\t<div class=\"about-box-0\">\r\n");
      out.write("\t\t\t\t<h1 class=\"normal-ntext margin-p\" style=\"font-weight: bolder;\">직장경력</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"about-box-1\">\r\n");
      out.write("\t\t\t\t<p class=\"normal-sltext\" style=\"margin-top: 5px; font-weight: bolder;\" >해윤파트너스 (2016. 11 - 2017. 12)</p>\r\n");
      out.write("\t\t\t\t<p class=\"normal-sltext\" style=\"margin-top: 5px;\" >디자인 & 마케팅 / 사원</p>\r\n");
      out.write("\t\t\t\t<p class=\"normal-sltext\" style=\"margin-top: 5px;\" >홈페이지 제작</p>\r\n");
      out.write("\t\t\t\t<p class=\"normal-sltext\" style=\"margin-top: 5px;\" >2017 미국 라스베가스 CES 박람회 해외 마케팅 참여</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<p class=\"normal-sltext\" style=\"margin-top: 30px; font-weight: bolder;\" >(주) 에어테크 (2020. 02 - 2021. 03)</p>\r\n");
      out.write("\t\t\t\t<p class=\"normal-sltext\" style=\"margin-top: 5px;\" >디자인 & 마케팅 / 이사</p>\r\n");
      out.write("\t\t\t\t<p class=\"normal-sltext\" style=\"margin-top: 5px;\" >자사 로고 제작</p>\r\n");
      out.write("\t\t\t\t<p class=\"normal-sltext\" style=\"margin-top: 5px;\" >자사 홈페이지 제작</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"about-box line-box\">\r\n");
      out.write("\t\t\t<div class=\"about-box-0\">\r\n");
      out.write("\t\t\t\t<h1 class=\"normal-ntext margin-p\" style=\"font-weight: bolder;\">교육 및 수료</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"about-box-1\">\r\n");
      out.write("\t\t\t\t<div class=\"about-box-31\">\r\n");
      out.write("\t\t\t\t\t<p class=\"normal-sltext margin-p\" style=\"font-weight: bolder;\" >2018</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"about-box-32\">\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<ul><p class=\"normal-sltext margin-p\" >창업멘토링 교육(포항창조경제혁신센터 주관)</p></ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"about-box-31\">\r\n");
      out.write("\t\t\t\t\t<p class=\"normal-sltext\" style=\"font-weight: bolder; margin-top: 30px;\" >2020</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"about-box-32\">\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<ul><p class=\"normal-sltext margin-p\" style=\"margin-top: 30px;\" >인공지능 기본과정(한국IT비즈니스진흥협회 주관)</p></ul>\r\n");
      out.write("\t\t\t\t\t\t<ul><p class=\"normal-sltext margin-p\" >경북 인공지능·사물인터넷 실무자과정(포스텍 인공지능연구원 주관)</p></ul>\r\n");
      out.write("\t\t\t\t\t\t<ul><p class=\"normal-sltext margin-p\" >웹 프로그래밍 기초과정(포스텍 주관)</p></ul>\r\n");
      out.write("\t\t\t\t\t\t<ul><p class=\"normal-sltext margin-p\" >웹 프로그래밍Ⅱ(포스텍 주관)</p></ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"about-box line-box\">\r\n");
      out.write("\t\t\t<div class=\"about-box-0\">\r\n");
      out.write("\t\t\t\t<h1 class=\"normal-ntext margin-p\" style=\"font-weight: bolder;\">자격증</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"about-box-1\">\r\n");
      out.write("\t\t\t\t<div class=\"about-box-31\">\r\n");
      out.write("\t\t\t\t\t<p class=\"normal-sltext margin-p\" style=\"font-weight: bolder;\" >2018</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"about-box-32\">\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<ul><p class=\"normal-sltext margin-p\" >국가공인 ITQ(정보기술자격) 아래한글 A(한국생산성본부 주관)</p></ul>\r\n");
      out.write("\t\t\t\t\t\t<ul><p class=\"normal-sltext margin-p\" >국가공인 ITQ(정보기술자격) 한글파워포인트 A(한국생산성본부 주관)</p></ul>\r\n");
      out.write("\t\t\t\t\t\t<ul><p class=\"normal-sltext margin-p\" >국가공인 ITQ(정보기술자격) 한글엑셀 B(한국생산성본부 주관)</p></ul>\r\n");
      out.write("\t\t\t\t\t\t<ul><p class=\"normal-sltext margin-p\" >국가공인 ITQ(정보기술자격) 인터넷 A(한국생산성본부 주관)</p></ul>\r\n");
      out.write("\t\t\t\t\t\t<ul><p class=\"normal-sltext margin-p\" >국가공인 문서실무사(KB) 1급(한국정보관리협회 주관)</p></ul>\r\n");
      out.write("\t\t\t\t\t\t<ul><p class=\"normal-sltext margin-p\" >코딩지도사 1급(한국교육진흥협회 주관)</p></ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"about-box-31\">\r\n");
      out.write("\t\t\t\t\t<p class=\"normal-sltext\" style=\"font-weight: bolder; margin-top: 30px;\" >2019</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"about-box-32\">\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<ul><p class=\"normal-sltext margin-p\"  style=\"margin-top: 30px;\" >국가공인 IEQ(인터넷윤리자격) 지도사(한국생산성본부 주관)</p></ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"about-box line-box\">\r\n");
      out.write("\t\t\t<div class=\"about-box-0\">\r\n");
      out.write("\t\t\t\t<h1 class=\"normal-ntext margin-p\" style=\"font-weight: bolder;\">수상경력</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"about-box-1\">\r\n");
      out.write("\t\t\t\t<p class=\"normal-sltext\" style=\"margin-top: 5px;\" >제4회 경북 학생 영상제 - 동상(경상북도교육청, 안동문화방송 주관)</p>\r\n");
      out.write("\t\t\t\t<p class=\"normal-sltext\" style=\"margin-top: 5px;\" >제7회 낙동강전국청소년영상제 - 입상(매일신문사 주관) [친구]</p>\r\n");
      out.write("\t\t\t\t<p class=\"normal-sltext\" style=\"margin-top: 5px;\" >제7회 낙동강전국청소년영상제 - 입상(매일신문사 주관) [대동고 축제홍보]</p>\r\n");
      out.write("\t\t\t\t<p class=\"normal-sltext\" style=\"margin-top: 5px;\" >표창장(제37사단 공병대대)</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"about-box line-box\">\r\n");
      out.write("\t\t\t<div class=\"about-box-0\">\r\n");
      out.write("\t\t\t\t<h1 class=\"normal-ntext margin-p\" style=\"font-weight: bolder;\">병역</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"about-box-1\">\r\n");
      out.write("\t\t\t\t<div class=\"about-box-31\">\r\n");
      out.write("\t\t\t\t\t<p class=\"normal-sltext margin-p\" style=\"font-weight: bolder;\" >군별</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"about-box-32\">\r\n");
      out.write("\t\t\t\t\t<p class=\"normal-sltext margin-p\" >육군</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t<div class=\"about-box-31\">\r\n");
      out.write("\t\t\t\t\t<p class=\"normal-sltext margin-p\" style=\"font-weight: bolder;\" >복무기간</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"about-box-32\">\r\n");
      out.write("\t\t\t\t\t<p class=\"normal-sltext margin-p\" >2018. 05. 18 - 2020. 01. 02</p>\r\n");
      out.write("\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"about-box-31\">\r\n");
      out.write("\t\t\t\t\t<p class=\"normal-sltext margin-p\" style=\"font-weight: bolder;\" >계급</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"about-box-32\">\r\n");
      out.write("\t\t\t\t\t<p class=\"normal-sltext margin-p\" >병장</p>\r\n");
      out.write("\t\t\t\t</div> \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"about-box-31\">\r\n");
      out.write("\t\t\t\t\t<p class=\"normal-sltext margin-p\" style=\"font-weight: bolder;\" >병역</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"about-box-32\">\r\n");
      out.write("\t\t\t\t\t<p class=\"normal-sltext margin-p\" >만기전역</p>\r\n");
      out.write("\t\t\t\t</div> \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/src/footer.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/src/page_up_btn.jsp", out, false);
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
